#!/usr/bin/with-contenv bash
# shellcheck shell=bash

echo -e "[init-geoip2influx-setup] Starting"

echo -e "[init-geoip2influx-setup] Variables set:\\n\
NGINX_LOG_PATH=${NGINX_LOG_PATH}\\n\
INFLUX_HOST=${INFLUX_HOST}\\n\
INFLUX_HOST_PORT=${INFLUX_HOST_PORT}\\n\
INFLUX_DATABASE=${INFLUX_DATABASE}\\n\
INFLUX_USER=${INFLUX_USER}\\n\
INFLUX_PASS=${INFLUX_PASS}\\n\
INFLUX_RETENTION=${INFLUX_RETENTION}\\n\
INFLUX_SHARD=${INFLUX_SHARD}\\n\
GEO_MEASUREMENT=${GEO_MEASUREMENT}\\n\
LOG_MEASUREMENT=${LOG_MEASUREMENT}\\n\
SEND_NGINX_LOGS=${SEND_NGINX_LOGS}\\n\
GEOIP2INFLUX_LOG_LEVEL=${GEOIP2INFLUX_LOG_LEVEL}\\n\
GEOIP2INFLUX_LOG_PATH=${GEOIP2INFLUX_LOG_PATH}\\n\
MAXMINDDB_USER_ID=${MAXMINDDB_USER_ID}\\n\
MAXMINDDB_LICENSE_KEY=${MAXMINDDB_LICENSE_KEY}\\n"

mkdir -p \
  /config/log/geoip2influx
cp -rf /geoip2influx /config/geoip2db
cp -f /geoip2influx/run.py /config/geoip2db
# move old log if needed
if [ -f /config/geoip2db/geoip2influx.log ]; then
  echo -e "[init-geoip2influx-setup] Moving old log"
  mv /config/geoip2db/geoip2influx.log /config/log/geoip2influx
fi

lsiown -R abc:abc /config/geoip2db
chmod +x /config/geoip2db/run.py
chmod -R 0644 /etc/logrotate.d

echo -e "[init-geoip2influx-setup] Finished"